version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 602192780151.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 602192780151.dkr.ecr.ap-south-1.amazonaws.com/ecs-package-repository
  post_build:
    commands:
      - docker push 602192780151.dkr.ecr.ap-south-1.amazonaws.com/ecs-package-repository
      - printf '[{"name":test,"imageUri":"%s"}]' 602192780151.dkr.ecr.ap-south-1.amazonaws.com/ecs-package-repository > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
